repos:
  - repo: local
    hooks:
      - id: linting
        name: invoke linting
        entry: invoke
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
        args:
          - linting
