name: Python package

on:
  release:
    types:
      - released

jobs:
  package-bg-aws-utils:
    runs-on: ubuntu-latest
    env:
      PIP_INDEX_URL: https://${{ secrets.PIP_INDEX_USERNAME }}:${{ secrets.PIP_INDEX_PASSWORD }}@metoffice.jfrog.io/metoffice/api/pypi/pypi/simple
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          ref: main

      - name: Cache pip downloads
        uses: actions/cache@v2
        env:
          cache-name: pip-wheel-cache-for-packaging
        with:
          path: ~/.cache/pip # for Unix/Linux
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements/*') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements-dev.txt
        working-directory: requirements/ # In case of relative references

      - name: Invoke build
        run: invoke build

      - name: Invoke publish
        run: invoke publish
        env:
          TWINE_USERNAME: ${{ secrets.PIP_INDEX_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PIP_INDEX_PASSWORD }}
          TWINE_REPOSITORY_URL: https://metoffice.jfrog.io/metoffice/api/pypi/pypi/simple
          TWINE_NON_INTERACTIVE: "True" # Value not really needed, just needs to be set
