name: Unit Tests

on: [push, workflow_dispatch]

jobs:

  run-unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    env:
      PIP_INDEX_URL: https://${{ secrets.PIP_INDEX_URL_USERNAME_AND_ACCESS_TOKEN }}@metoffice.jfrog.io/metoffice/api/pypi/pypi/simple
    steps:
      - name: Checkout repo
        with:
          # Disabling shallow clone is recommended by SonarCloud for improving relevancy of reporting
          fetch-depth: 0
        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Cache pip downloads
        uses: actions/cache@v2
        env:
          CACHE_NAME: pip-wheel-cache-for-unit-tests
          PYTHON_PROJECT: cdkutils
        with:
          path: ~/.cache/pip # for Unix/Linux
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ env.PYTHON_PROJECT }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements-tox.txt
        working-directory: requirements/ # In case of relative references

      - name: Run tests with coverage
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials

          echo "[default]
          aws_access_key_id = dummy
          aws_secret_access_key = dummy
          region = eu-west-2" > ~/.aws/credentials

          tox

      - name: Override Coverage Source Path for Sonar
        # This is because the report is generated outside the docker container the sonarcloud action runs in,
        # so has different paths
        run: sed -i "s|${GITHUB_WORKSPACE}|/github/workspace|g" coverage.xml

      - name: Override Tox Path for Sonar
        # This is because the file paths are generated for inside the tox package, so sonarcloud has different paths
        run: sed -i "s|.tox/py38/lib/python3.8/site-packages|src|g" coverage.xml

      - name: Run sonarcloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
